FROM debian:bookworm

RUN apt-get -o Acquire::Check-Valid-Until=false update && \
    apt-get install -y apache2 ca-certificates tinyproxy systemd systemd-sysv && \
    apt-get remove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkfifo /pipe
