FROM rockylinux:9

ENV container docker

RUN dnf install systemd httpd diffutils wget -y && \
    wget https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/t/tinyproxy-1.11.1-1.el9.x86_64.rpm && \
    rpm -i tinyproxy-1.11.1-1.el9.x86_64.rpm && \
    rm -f *.rpm && dnf -y remove wget

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*;\
    rm -f /etc/systemd/system/*.wants/*;\
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*;\
    rm -f /lib/systemd/system/anaconda.target.wants/*;

CMD ["/usr/sbin/init"]

RUN systemctl enable httpd
RUN systemctl enable tinyproxy
RUN chmod 700 ~root
RUN mkfifo /pipe
