name: "Build binaries - release"
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: Release Go Binary
    runs-on: ubuntu-latest
    permissions:
      contents: writee

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Get tag
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: echo "TRAVIS_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
      - run: make release
      - run: make dgoss-sha256
      - uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: |
            release/*
            extras/**/*goss
            extras/**/*goss.sha256
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/*
            extras/**/*goss
            extras/**/*goss.sha256
