name: "Build binaries - release"
on:
  # debug
  pull_request: {}
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Release Go Binary
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Get version from tag
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: echo "TRAVIS_TAG=${{ github.ref_name }}" >> $GITHUB_ENV

      - run: make release
      - run: make dgoss-sha256

      - name: Create release and upload assets
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/*
            extras/*/*goss
            extras/*/*goss.sha256
