name: "Build binaries"
on:
  # don't build any branch other than master (and prs) when git pushed
  pull_request: {}
  push:
    branches:
      - master
      - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Prepare windows
        run: choco install make
      - name: Install
        run: ci/install.sh
      - name: Build
        run: make "test-windows-all"

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Install
        run: ci/install.sh
      - name: Before build
        run: ./cc-test-reporter before-build
      - name: Build
        run: make "test-darwin-all"
      - name: Report failed build
        if: failure()
        run: ./cc-test-reporter after-build --exit-code 1 -d
      - name: Report successful build
        if: success()
        run: ./cc-test-reporter after-build --exit-code 0 -d

  build-linux:
    services:
      docker:
        image: docker:dind
        options: --privileged
        ports:
          - 2375:2375
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Install Docker
        run: |
         sudo apt-get update
         curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
         echo \
           "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
           $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
         sudo apt-get install docker-ce-clil

      - name: Test connection
        run: |
          sudo apt-get update
          sudo apt-get install -y iputils-ping
          ping -c 3 docker

      - name: Test Docker
        run: |
          docker version
          docker info

      - name: Install
        run: ci/install.sh
      - name: Before build
        run: ./cc-test-reporter before-build
      - name: Build
        run: ci/build.sh
      - name: Report failed build
        if: failure()
        run: ./cc-test-reporter after-build --exit-code 1 -d
      - name: Report successful build
        if: success()
        run: ./cc-test-reporter after-build --exit-code 0 -d

