name: "Build binaries"
on:
  # don't build any branch other than master (and prs) when git pushed
  pull_request: {}
  push:
    branches:
      - master
      - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
jobs:
#  build-windows:
#    runs-on: windows-latest
#    strategy:
#      fail-fast: false
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-go@v4
#        with:
#          go-version: "1.21"
#      - name: Prepare windows
#        run: choco install make
#      - name: Install
#        run: ci/install.sh
#      - name: Build
#        run: make "test-windows-all"

#  build-macos:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-go@v5
#        with:
#          go-version: "1.21"
#      - name: Install
#        run: ci/install.sh
#      - name: Before build
#        run: ./cc-test-reporter before-build
#      - name: Build
#        run: make "test-darwin-all"
#      - name: Report failed build
#        if: failure()
#        run: ./cc-test-reporter after-build --exit-code 1 -d
#      - name: Report successful build
#        if: success()
#        run: ./cc-test-reporter after-build --exit-code 0 -d

  build-linux:
    runs-on: ubuntu-latest
    services:
      redis:
        image: docker:dind
        options: --privileged
        ports:
        - 8075:2375
        - 8076:2376
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
#      - name: golangci-lint
#        uses: golangci/golangci-lint-action@v5
#        with:
#          version: latest
      - name: Install
        run: ci/install.sh
      - name: Before build
        run: ./cc-test-reporter before-build
      - name: Build
        run: |
          #export
          #pwd
          docker info
          ci/build.sh
        env:
          DOCKER_HOST: tcp://127.0.0.1:8076
      - name: Report failed build
        if: failure()
        run: ./cc-test-reporter after-build --exit-code 1 -d
      - name: Report successful build
        if: success()
        run: ./cc-test-reporter after-build --exit-code 0 -d

