name: "Build binaries"
on:
  # don't build any branch other than master (and prs) when git pushed
  pull_request: {}
  push:
    branches:
      - master
      - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Prepare windows
        run: choco install make
      - name: Install
        run: ci/install.sh
      - name: Build
        run: make "test-windows-all"

  build:
    services:
      if: matrix.os == 'ubuntu-latest'
      docker:
        image: docker:dind
    runs-on: ${{ matrix.os }}
    strategy:
      #fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Install
        run: ci/install.sh
      - name: Before build
        run: ./cc-test-reporter before-build
      - name: Build
        run: ci/build.sh
      - name: Report failed build
        if: failure()
        run: ./cc-test-reporter after-build --exit-code 1 -d
      - name: Report successful build
        if: success()
        run: ./cc-test-reporter after-build --exit-code 0 -d

