name: Create docker images and push to ghcr.io

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docker:
    name: Push Docker image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./integration-tests/Dockerfile_alpine3
            image: goss_alpine3
          - dockerfile: ./integration-tests/Dockerfile_arch
            image: goss_arch
          - dockerfile: ./integration-tests/Dockerfile_centos7
            image: goss_centos7
          - dockerfile: ./integration-tests/Dockerfile_trusty
            image: goss_trusty
          - dockerfile: ./integration-tests/Dockerfile_wheezy
            image: goss_wheezy
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}

      - name: Build and Push Tag
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64